version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - nilnil
    - paralleltest
    - wsl

  settings:
    funcorder:
      alphabetical: true

formatters:
  enable:
    - gofumpt
    - goimports
